import {theme} from "@/theme/theme";
import { ThemeProvider } from "@mui/material/styles";
import type { Metadata } from "next";
import {Geist_Mono,Sofia_Sans} from "next/font/google";
import "../globals.css";

const sofiaPro = Sofia_Sans({
    variable: "--font-sofia-pro",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${sofiaPro.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </body>
        </html>
    );
}
